src/Entity/Tricks.php
<?php

namespace App\Entity;

use App\Repository\TricksRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=TricksRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity("slug",
 *     message="Ce Tricks existe déjà en base de donnée")
 */
class Tricks
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $author_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=0, minMessage="Vous devez donner un nom à votre tricks", allowEmptyString="false")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $update_at;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     *
     */
    private $main_image;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="tricks")
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity=Media::class, mappedBy="tricks",cascade={"persist","remove"})
     */
    private $media;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="tricks", orphanRemoval=true,cascade={"persist","remove"})
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=Video::class, mappedBy="tricks",cascade={"persist","remove"})
     */
    private $videos;

    private $path;


    /**
     * @Assert\Image(
     *      maxSize = "1M",
     *      maxSizeMessage = "L'image principal ne doit pas dépasser 1 Mo",
     *      minWidth="600",
     *      minWidthMessage="L'image principal doit faire plus de 600 px",
     *      mimeTypes={"image/jpeg","image/jpg"},
     *      mimeTypesMessage="L'extension ({{ type }}) est invalide. Seul l'extension {{ types }} est acceptée."
     * )
     */
    private $file;

    private $old_path;

    /**
     * @return mixed
     */
    public function getOldPath()
    {
        return $this->old_path;
    }

    /**
     * @param mixed $old_path
     */
    public function setOldPath($old_path): void
    {
        $this->old_path = $old_path;
    }
    public function __construct()
    {
        $this->category = new ArrayCollection();
        $this->media = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->videos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthorId(): ?User
    {
        return $this->author_id;
    }

    public function setAuthorId(?User $author_id): self
    {
        $this->author_id = $author_id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->update_at;
    }

    public function setUpdateAt(?\DateTimeInterface $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getMainImage(): ?string
    {
        return $this->main_image;
    }

    public function setMainImage(string $main_image): self
    {
        $this->main_image = $main_image;

        return $this;
    }

    public function getPath()
    {
        return $this->path;
    }

    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->category->contains($category)) {
            $this->category[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->category->removeElement($category);

        return $this;
    }

    /**
     * @return Collection|Media[]
     */
    public function getMedia(): Collection
    {
        return $this->media;
    }

    public function addMedium(Media $medium): self
    {
        if (!$this->media->contains($medium)) {
            $this->media[] = $medium;
            $medium->setTricks($this);
        }

        return $this;
    }

    public function removeMedium(Media $medium): self
    {
        if ($this->media->removeElement($medium)) {
            // set the owning side to null (unless already changed)
            if ($medium->getTricks() === $this) {
                $medium->setTricks(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTricks($this);
        }
        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getTricks() === $this) {
                $comment->setTricks(null);
            }
        }
        return $this;
    }

    /**
     * @return Collection|Video[]
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setTricks($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getTricks() === $this) {
                $video->setTricks(null);
            }
        }
        return $this;
    }


    public function getFile()
    {
        return $this->file;
    }

    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;

        return $this;
    }

    /**
     * @ORM\PreFlush()
     */
    public function handleFile()
    {
        if ($this->file === null) {
            return;
        }
        // Delete image from the server if update
        if ($this->id && $this->main_image !== 'default-image.jpg' && file_exists($this->path.$this->old_path)) {
            unlink( $this->path.$this->old_path);
        }
        // Moving image into the image repository
        $this->file->move($this->path, $this->main_image);
    }

    /**
     * @ORM\PreRemove()
     */
    public function handleFileDelete()
    {
        // Delete image from the server if delete the trick && if file with this name exist
        if ($this->id && ($this->main_image !== 'default-image.jpg') && file_exists($this->path.$this->old_path)) {
            unlink( $this->path.$this->old_path);
        }
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(
 *     fields={"email"},
 *     message="Cette adresse mail est déjà utilisé sur la plateforme"
 * )
 * @ORM\HasLifecycleCallbacks()
 */
class User implements UserInterface
{
    const ROLE_ADMIN = 'ROLE_ADMIN';
    const ROLE_USER = 'ROLE_USER';
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email
     */
    private $email;

    /**
     * @ORM\Column(type="string" , length=60)
     */
    private $roles = self::ROLE_USER;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\NotBlank(
     *      message = "Ce champ est requis !"
     * )
     * @Assert\Length(
     *      min = 8,
     *      max = 254,
     *      minMessage = "Votre mot de passe doit contenir au moins 8 caractères.",
     *      maxMessage = "Votre mot de passe ne peut pas contenir plus que {{ limit }} caractères !"
     * )
     * @Assert\Regex(
     *     pattern = "^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*\W)^",
     *     match = true,
     *     message = "Le mot de passe doit contenir au moins une minuscule, une majuscule, un chiffre et un caractère spécial !"
     * )
     */
    private $password;
    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true,cascade={"persist","remove"})
     */
    private $comments;
    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author_id", orphanRemoval=true,cascade={"persist","remove"})
     */
    private $tricks;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $fname;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $lname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $avatar = 'avatar-default.jpg';

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $devise;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_create;

    /**
     * @ORM\Column(type="boolean")
     */
    private $rgpd;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif = 0 ;

    /**
     * @return mixed
     */
    public function getActif()
    {
        return $this->actif;
    }

    /**
     * @param mixed $actif
     */
    public function setActif($actif): void
    {
        $this->actif = $actif;
    }

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_expir_token;

    private $path_directory;

    /**
     * @return mixed
     */
    public function getPathDirectory()
    {
        return $this->path_directory;
    }

    /**
     * @param mixed $path_directory
     */
    public function setPathDirectory($path_directory): void
    {
        $this->path_directory = $path_directory;
    }

    private $file;

    private $old_avatar;

    /**
     * @return mixed
     */
    public function getOldAvatar()
    {
        return $this->old_avatar;
    }

    /**
     * @param mixed $old_avatar
     */
    public function setOldAvatar($old_avatar): void
    {
        $this->old_avatar = $old_avatar;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {

        return [$this->roles];
    }
  /**
     * @see UserInterface
     */
    public function getRole(): string
    {

        return $this->roles;
    }

    public function setRoles(string $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFname(): ?string
    {
        return $this->fname;
    }

    public function setFname(string $fname): self
    {
        $this->fname = $fname;

        return $this;
    }

    public function getLname(): ?string
    {
        return $this->lname;
    }

    public function setLname(string $lname): self
    {
        $this->lname = $lname;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getDevise(): ?string
    {
        return $this->devise;
    }

    public function setDevise(?string $devise): self
    {
        $this->devise = $devise;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDateCreate(): ?\DateTimeInterface
    {
        return $this->date_create;
    }

    public function setDateCreate(\DateTimeInterface $date_create): self
    {
        $this->date_create = $date_create;

        return $this;
    }

    public function getRgpd(): ?bool
    {
        return $this->rgpd;
    }

    public function setRgpd(bool $rgpd): self
    {
        $this->rgpd = $rgpd;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getDateExpirToken(): ?\DateTimeInterface
    {
        return $this->date_expir_token;
    }

    public function setDateExpirToken(?\DateTimeInterface $date_expir_token): self
    {
        $this->date_expir_token = $date_expir_token;

        return $this;
    }
    public function getFile()
    {
        return $this->file;
    }

    public function setFile(UploadedFile $file = null)
    {
        $this->file= $file;

        return $this;
    }
    /**
     * @ORM\PreFlush()
     */
    public function handleFile()
    {
        if ($this->file === null) {
            return;
        }
        // Delete avatar from the server if update
        if ($this->id && $this->avatar !== 'avatar-default.jpg' && file_exists($this->path_directory.$this->old_avatar)) {
            unlink( $this->path_directory.$this->old_avatar);
        }

         //Moving image into the image repository
        $this->file->move($this->path_directory, $this->avatar);
    }

    /**
     * @ORM\PreRemove()
     */
    public function handleFileDelete()
    {
        // Delete image from the server if delete the trick && if file with this name exist
        if ($this->id && $this->avatar !== 'avatar.jpg' && file_exists($this->path_directory.$this->old_avatar)) {
            unlink( $this->path_directory.$this->old_avatar);
        }
    }
}

templates/tricks/show.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ tricks.name }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10 col-md-offset-1 mb-4">
                <div class="card mt-5">
                    <img class="display-top img-fluid" src="/asset/media/main{{ asset(tricks.mainimage) }}" alt="{{ tricks.name }}-main">
                    <div class="card-body">
                        <ul class="list-inline trick-data mb-5">
                            <li class="list-inline-item">
                                Par : <a target="" {#href="{{ path('user_profile', {'id' : tricks.authorid} ) }}"#}>{{ tricks.authorId.lname }} {{ tricks.authorId.fname }}</a>
                            </li> |
                            <li class="list-inline-item mr-3">
                                Ajouté le {{ tricks.createdAt | date('d/m/Y') }}  {% if tricks.updateAt is not null %}(<small>Mise à jour le : {{ tricks.updateAt | date('d/m/Y') }} </small>){% endif %}
                            </li>
                            <li class="list-inline-item ">
                                <div class="row">
                                    Catégorie :
                                    {% for cat in tricks.category %}
                                        <div class="ml-2 hoverShow">
                                     <span class="badge badge-pill badge-warning mr-2">
                                    {{ cat.name}}
                                     </span>
                                            <p class="text-warning mouseHoverShow"> {{ cat.description}}</p>
                                        </div>
                                    {% endfor %}
                                </div>

                            </li> |
                            <li class="list-inline-item">
                                <a id="encreComments">{{ tricks.comments|length }} commentaires</a>
                            </li>
                        </ul>
                        <hr>
                        <!-- Bouton screen mobil -->
                        <button id="seeMedia" type="button" class="btn btn-warning seeMedia">Voir les médias</button>
                        <!-- Start Carousel -->
                        <div id="carMedia" class="row  d-lg-flex load-media ">
                            {% if tricks.media is defined %}
                            <div class="col-lg-6 col-md-12">
                                <div id="carousel_image" class="carousel slide mt-3 mb-2" data-ride="carousel">
                                     <ol class="carousel-indicators">
                                     {% for img in tricks.media %}
                                         {% if img.type =='img' %}
                                             <li data-target=".carousel" data-slide-to="{{ loop.index - 1 }}"  {% if loop.index != 0 %}class="active" {% endif %}></li>
                                         {% endif %}
                                     {% endfor %}
                                 </ol>
                                 <div class="carousel-inner enlarge">
                                     {% for img in tricks.media %}
                                         <div class="carousel-item{% if loop.index == 1 %} active {% endif %}">
                                             <img class="d-block mediaSize" src="/asset/media/img{{ asset(img.path) }}" alt="{{ asset(img.name) }}">
                                         </div>
                                     {% endfor %}
                                 </div>
                                    {% if tricks.media|length > 1 %}
                                        <a class="carousel-control-prev" href="#carousel_image" data-slide="prev">
                                            <span class="carousel-control-prev-icon"></span>
                                        </a>
                                        <a class="carousel-control-next" href="#carousel_image" data-slide="next">
                                            <span class="carousel-control-next-icon"></span>
                                        </a>
                                    {% endif%}
                                </div>
                            </div>
                            {% endif %}

                            {% if tricks.videos is defined %}
                            <div class="col-lg-6 col-md-12">
                                <div id="carousel-v" class="carousel slide mt-3 mb-2" data-ride="carousel">
                                    <ol class="carousel-indicators">
                                        {% for video in tricks.videos %}
                                                <li data-target=".carousel"  data-slide-to="{{ loop.index - 1 }}"  {% if loop.index != 0 %}class="active" {% endif %}></li>
                                        {% endfor %}
                                    </ol>
                                    <div class="carousel-inner toto ">
                                        {% for video in tricks.videos %}
                                                <div class="carousel-item {% if loop.last %} active {% endif %}">
                                                    <iframe class="mediaSize" src="{{ asset(video.path) }}" title="YouTube video player"  allowfullscreen></iframe>
                                                </div>
                                        {% endfor %}
                                    </div>
                                    {% if tricks.videos|length > 1 %}
                                        <a class="carousel-control-prev" href="#carousel-v" data-slide="prev">
                                            <span class="carousel-control-prev-icon"></span>
                                        </a>
                                        <a class="carousel-control-next" href="#carousel-v" data-slide="next">
                                            <span class="carousel-control-next-icon"></span>
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                            {% endif %}

                        <!-- End Carousel -->
                        <hr>
                        <h4 class="card-title  p-3"><strong>{{ tricks.name }}</strong></h4>
                        <p class="card-text text-justify p-3"><strong>{{ tricks.description }}</strong></p>
                    </div>
                </div>
                      <!-- Start Comment Add Form -->
                      {% if app.user %}
                          <div class="col-lg-12 px-0 mt-3 mb-3 bg-light">
                              <div class="border entry-comments">
                                  <h2 class="h4 col pt-3">Ecrivez un commentaire</h2>
                                  <hr>
                                  <p class="col">Bonjour {{ app.user.username }} !</p>
                                  {{ form_start(form) }}
                                  <div class="form-group col">
                                      {{ form_row(form.content) }}
                                  </div>
                                  <div class="form-group text-center">
                                      <button type="submit" class="btn btn-success mt-3">Commenter</button>
                                  </div>
                                  {{ form_end(form) }}
                              </div>
                          </div>
                      {% else %}
                          <div class="col-md-12 px-0 mb-3">
                              <div class="comments text-center p-3">
                                  <p><a href="">Inscrivez-vous</a> ou <a href="{{ path('app_login') }}">connectez vous</a> pour commenter cet article</p>
                          </div>
                    </div>
                    {% endif %}
                <!-- Start Comment Add Form -->

                <!-- Start Comments -->
                <span class="comments-anchor" id="comments-block"></span>
                <div class="col-md-12 bg-light " >
                    <div class="mb-3" >
                        <div id="divComment" class="border entry-comments">
                            <ul id="comments-title" class="entry-comments-list list-unstyled">
                                {% for comment in comments %}
                                    <div  class=" mb-3 pl-2 bg-light  hidden-comments comment"  style="display: none">
                                        <div class="row">
                                            <span class="comment-anchor" id="{{ comment.id }}"></span>
                                            <div class="col-lg-3 text-center p-5">
                                                <img src="/asset/media/avatar{{ asset(comment.author.avatar) }}" class="user-profile" style="width: 100%" alt="{{ comment.author.fname}}">
                                            </div>
                                            <div class="col-lg-9 p-5">
                                                <p>
                                                    <span><strong> Commenté le {{ comment.dateCreate|date('d/m/Y') }} par <a href="" style="color: #0a0b0d" >{{ comment.author.lname }}</a></strong></span>
                                                    <span class="date mr-2">
                                                 il y a
                                                {% set difference = date(comment.dateCreate|date('Y/m/d')).diff(date('now'|date('Y/m/d'))) %}
                                                        {% set leftDays = difference.days %}
                                                        {% if leftDays == 1 %}
                                                            1 jour
                                                        {% elseif leftDays == 0 %}
                                                            moins de 24 heures
                                                        {% else %}
                                                            {{ leftDays }} jours
                                                        {% endif %}
                                            </span>
                                                </p>
                                                <p>{{ comment.content }}</p>
                                            </div>
                                            <hr>
                                        </div>
                                    </div>
                                {% endfor %}
                            </ul>
                        </div>
                        {% if tricks.comments|length > 3 %}
                            <div class="row d-flex justify-content-center">
                                <div class="btn btn-info" id="loadMoreC" >Voir plus</div>
                                <div class="btn btn-info" id="loadLessC" style="display:none" >-</div>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <!-- End Comments -->
                    <div class="module_progress_comments container">
                        <div class="progress ">
                            <div id="tricksBarr" class="progress-bar progress-bar-striped progress-bar-animated bg-warning" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" ></div>
                        </div>
                        <div class="row d-flex justify-content-center">
                            <div class="btn btn-info" id="loadMoreC" >+</div>
                            <div class="btn btn-info" id="loadLessC" style="display:none" >-</div>
                        </div>
                        <div class="text-right">
                            <a id="upC" class="home-link-bottom cursor" title="Aller en haut de la page">
                                <i class="fas fa-chevron-up fa-3x chevron-up"></i>
                            </a>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}